In [6]:
import pandas as pd

### Import four CSV files

In [7]:
routes = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/routes.csv")
routes.head()

,route_id,route_name,mode,district,route_length_km,scheduled_trips_per_day
0,R001,Angel Harbor Line,tram,Harbourside,19.8,133
1,R002,Jeffrey Street Line,BUS,NaN,12.6,80
2,R003,Erica Plains Line,METRO,Southbank,4.3,203
3,R004,Brittany Bypass Line,Tram,Northgate,17.6,131
4,R005,Clayton Fort Line,bus,NaN,5.0,159

In [8]:
stops = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/stops.csv")
stops.head()

  stop_id            stop_name   district    zone has_shelter
0   S0001  matthew radial stop  Riverside  Zone 2           N
1   S0002  Brianna Avenue Stop     Centro  Zone 3           1
2   S0003     jean circle stop  Northgate  Zone 2           0
3   S0004   Carlos Bypass Stop   Old Town  Zone 1           Y
4   S0005   JONES FREEWAY STOP  Riverside  Zone 2           N

In [9]:
validations = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/validations.csv")
validations.head()

,validation_id,validation_ts,route_id,vehicle_id,stop_id,card_id,fare_type,fare_amount,passenger_count,transfer_flag
0,VAL-0068918,2024-05-13 18:54:29,R001,V0044,S0234,CARD-001739,Full Fare,2.53,1.0,N
1,VAL-0044034,06/06/2024 08:48,R058,V0086,S0131,CARD-000729,ADULT,2.48,1.0,Y
2,VAL-0017450,06/03/2024 13:15,R043,V0177,S0251,CARD-020205,Adult,2.85,1.0,FALSE
3,VAL-0004736,2024-04-21 17:30:00,R026,V0108,S0330,CARD-013092,student,1.64,3.0,Y
4,VAL-0053735,2024-06-14 18:35:27,R003,V0057,S0389,CARD-003251,Student,1.34,1.0,0

In [10]:
vehicles = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/vehicles.csv")
vehicles.head()

  vehicle_id     vehicle_type  capacity  year_manufactured            depot
0      V0001  Articulated Bus     125.0               2021    Central Depot
1      V0002     Standard Bus       NaN               1998       East Depot
2      V0003  Articulated Bus     118.0               2022    Central Depot
3      V0004             Tram     170.0               2008    Central Depot
4      V0005     Standard Bus      73.0               2013  Riverside Depot

###### The four datasets were loaded successfully

#### Reading CSV Files with dtype 
###### The project contains four raw CSV files: routes, stops, validations and vehicles. The data will be loaded with explicit data types so that IDs remain strings.

In [9]:
routes= pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/routes.csv",
                    dtype={"route_id": "string",
                           "route_name": "string",
                           "mode": "string",
                           "district":"string",
                           "route_length_km":"float64",
                           "scheduled_trips_per_day":"Int64"}
                           )
routes.dtypes

route_id                    string
route_name                  string
mode                        string
district                    string
route_length_km            float64
scheduled_trips_per_day      Int64
dtype: object

In [16]:
stops = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/stops.csv",
                    dtype={"stop_id":"string",
                           "stop_name":"string",
                           "district":"string",
                           "zone":"string",
                           "has_shelter":"string"
                           }
                           )
stops.dtypes

stop_id        string
stop_name      string
district       string
zone           string
has_shelter    string
dtype: object

In [13]:
validations = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/validations.csv",
                          dtype={"validation_id":"string",
                                 "validation_ts":"string",
                                 "route_id":"string",
                                 "vehicle_id":"string",
                                 "stop_id":"string",
                                 "card_id":"string",
                                 "fare_type":"string",
                                 "fare_amount":"float64",
                                 "passenger_count": "float64",
                                 "transfer_flag": "float64",
                                "transfer_flag": "string"
                                }
)
validations.dtypes

validation_id       string
validation_ts       string
route_id            string
vehicle_id          string
stop_id             string
card_id             string
fare_type           string
fare_amount        float64
passenger_count    float64
transfer_flag       string
dtype: object

In [18]:
vehicles = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/vehicles.csv",
                       dtype={"vehicle_id":"string",
                              "vehicle_type":"string",
                              "capacity": "float64",
                              "year_manufactured":"int64",
                              "depot":"string"}
                              )
vehicles.dtypes

vehicle_id            string
vehicle_type          string
capacity             float64
year_manufactured      int64
depot                 string
dtype: object

### Missing values

In [ ]:
try:
    routes=pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/routes.csv",
                       dtype={"route_id": "string",
                               "route_name": "string",
                               "mode": "string",
                               "district":"string",
                               "route_length_km":"float64",
                               "scheduled_trips_per_day":"Int64"}
                               )
except FileNotFoundError:
    print(f"File not found.")

In [21]:
try:
    stops = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/stops.csv",
                    dtype={"stop_id":"string",
                           "stop_name":"string",
                           "district":"string",
                           "zone":"string",
                           "has_shelter":"string"
                           }
                           )
except FileNotFoundError:
    print(f"File not found")

In [22]:
try:
    validations = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/validations.csv",
                          dtype={"validation_id":"string",
                                 "validation_ts":"string",
                                 "route_id":"string",
                                 "vehicle_id":"string",
                                 "stop_id":"string",
                                 "card_id":"string",
                                 "fare_type":"string",
                                 "fare_amount":"float64",
                                 "passenger_count": "float64",
                                 "transfer_flag": "float64",
                                "transfer_flag": "string"
                                }
)
except FileNotFoundError:
    print(f"File not found")

In [23]:
try:
    vehicles = pd.read_csv("data-analysis-bootcamp-capstone-project/data/raw/vehicles.csv",
                       dtype={"vehicle_id":"string",
                              "vehicle_type":"string",
                              "capacity": "float64",
                              "year_manufactured":"int64",
                              "depot":"string"}
                              )
except FileNotFoundError:
    print(f"File not found")

### Routes
#### These routes profiles below are used to show us how many rows and columns each table has, data types and missing values and also the memory usage.

In [ ]:
print("Rows", routes.shape[0])

print("Columns", routes.shape[1])

print("Data type:")
print(routes.dtypes)

print("Null Counts:")
print(routes.isna().sum())

print("Null percentage:")
print(routes.isna().mean()* 100)

print("Memory usage:")
print(routes.memory_usage(deep= True).sum(),"bytes")

print("First rows:")
display(routes.head())

In [33]:
print("Rows", stops.shape[0])

print("Columns", stops.shape[1])

print("Data type:")
print(stops.dtypes)

print("Null Counts:")
print(stops.isna().sum())

print("Null percentage:")
print(stops.isna().mean()* 100)

print("Memory usage:")
print(stops.memory_usage(deep= True).sum(),"bytes")

print("First rows:")
display(stops.head())

Rows 400
Columns 5
Data type:
stop_id        string
stop_name      string
district       string
zone           string
has_shelter    string
dtype: object
Null Counts:
stop_id        0
stop_name      0
district       0
zone           0
has_shelter    0
dtype: int64
Null percentage:
stop_id        0.0
stop_name      0.0
district       0.0
zone           0.0
has_shelter    0.0
dtype: float64
Memory usage:
113828 bytes
First rows:

  stop_id            stop_name   district    zone has_shelter
0   S0001  matthew radial stop  Riverside  Zone 2           N
1   S0002  Brianna Avenue Stop     Centro  Zone 3           1
2   S0003     jean circle stop  Northgate  Zone 2           0
3   S0004   Carlos Bypass Stop   Old Town  Zone 1           Y
4   S0005   JONES FREEWAY STOP  Riverside  Zone 2           N

In [34]:
print("Rows", validations.shape[0])

print("Columns", validations.shape[1])

print("Data type:")
print(validations.dtypes)

print("Null Counts:")
print(validations.isna().sum())

print("Null percentage:")
print(validations.isna().mean()* 100)

print("Memory usage:")
print(validations.memory_usage(deep= True).sum(),"bytes")

print("First rows:")
display(validations.head())

Rows 81600
Columns 10
Data type:
validation_id       string
validation_ts       string
route_id            string
vehicle_id          string
stop_id             string
card_id             string
fare_type           string
fare_amount        float64
passenger_count    float64
transfer_flag       string
dtype: object
Null Counts:
validation_id         0
validation_ts         0
route_id              0
vehicle_id            0
stop_id               0
card_id            9777
fare_type             0
fare_amount        1183
passenger_count     833
transfer_flag         0
dtype: int64
Null percentage:
validation_id       0.000000
validation_ts       0.000000
route_id            0.000000
vehicle_id          0.000000
stop_id             0.000000
card_id            11.981618
fare_type           0.000000
fare_amount         1.449755
passenger_count     1.020833
transfer_flag       0.000000
dtype: float64
Memory usage:
38399748 bytes
First rows:

,validation_id,validation_ts,route_id,vehicle_id,stop_id,card_id,fare_type,fare_amount,passenger_count,transfer_flag
0,VAL-0068918,2024-05-13 18:54:29,R001,V0044,S0234,CARD-001739,Full Fare,2.53,1.0,N
1,VAL-0044034,06/06/2024 08:48,R058,V0086,S0131,CARD-000729,ADULT,2.48,1.0,Y
2,VAL-0017450,06/03/2024 13:15,R043,V0177,S0251,CARD-020205,Adult,2.85,1.0,FALSE
3,VAL-0004736,2024-04-21 17:30:00,R026,V0108,S0330,CARD-013092,student,1.64,3.0,Y
4,VAL-0053735,2024-06-14 18:35:27,R003,V0057,S0389,CARD-003251,Student,1.34,1.0,0

In [35]:
print("Rows", vehicles.shape[0])

print("Columns", vehicles.shape[1])

print("Data type:")
print(vehicles.dtypes)

print("Null Counts:")
print(vehicles.isna().sum())

print("Null percentage:")
print(vehicles.isna().mean()* 100)

print("Memory usage:")
print(vehicles.memory_usage(deep= True).sum(),"bytes")

print("First rows:")
display(vehicles.head())

Rows 180
Columns 5
Data type:
vehicle_id            string
vehicle_type          string
capacity             float64
year_manufactured      int64
depot                 string
dtype: object
Null Counts:
vehicle_id            0
vehicle_type          0
capacity             12
year_manufactured     0
depot                 0
dtype: int64
Null percentage:
vehicle_id           0.000000
vehicle_type         0.000000
capacity             6.666667
year_manufactured    0.000000
depot                0.000000
dtype: float64
Memory usage:
34467 bytes
First rows:

  vehicle_id     vehicle_type  capacity  year_manufactured            depot
0      V0001  Articulated Bus     125.0               2021    Central Depot
1      V0002     Standard Bus       NaN               1998       East Depot
2      V0003  Articulated Bus     118.0               2022    Central Depot
3      V0004             Tram     170.0               2008    Central Depot
4      V0005     Standard Bus      73.0               2013  Riverside Depot

### Step 4 looking with value.counts to see if something looks wrong

##### In the routes[mode] column we are seeing values that appear to represent the same transport mode, but are written differntly.

In [24]:
routes["mode"].value_counts()

mode
bus       11
tram       9
BUS        9
Tram       9
Bus        8
BUS        6
metro      3
TRAM       2
Metro      2
METRO      1
Name: count, dtype: int64

##### The stops[has_shelter] column contains mixed representations of the same concept: Y\N and 1\0 values are present.

In [28]:
stops["has_shelter"].value_counts()

has_shelter
0    115
Y    102
N     96
1     87
Name: count, dtype: int64

##### In the validations[fare_type] column we can also notice that we are having values that are the same but written differently (for example: ADULT, adult and Adult, or Senior, senior and Senior Citizen...). This will be changed during the cleaning stage.

##### In the validations[transfer_flag] column we have again mixed representations of the same concept: Y\N 1\0 and TRUE\FALSE. They are all the same.

In [29]:
validations["fare_type"].value_counts()

fare_type
Full Fare         11405
ADULT             11317
Adult             11282
adult             11280
student            4077
STUDENT            4062
Student            3961
Senior             3251
Senior Citizen     3237
senior             3179
Kid                2202
child              2124
Child              2109
Pass Holder        2075
PassHolder         2032
Monthly Pass       2012
pass holder        1995
Name: count, dtype: int64

In [30]:
validations["transfer_flag"].value_counts()

transfer_flag
N        36888
Y        24596
0         8075
FALSE     5593
1         4053
TRUE      2395
Name: count, dtype: int64

#### The raw DataFrames will now be saved unchanged to the data/interim folder for the next notebook

In [35]:
from pathlib import Path

interim_path = Path("data-analysis-bootcamp-capstone-project/data/interim")
interim_path.mkdir(parents=True, exist_ok=True)

routes.to_csv(interim_path/"routes.csv", index=False)
stops.to_csv(interim_path/"stops.scv", index=False)
validations.to_csv(interim_path/"validations.scv", index=False)
vehicles.to_csv(interim_path/"vehicles.scv", index=False)

print("All four raw datasets  were saved to data/interim/")

All four raw datasets  were saved to data/interim/